# site settings
title: Dudley Raine, IV
subtitle: homepage
email: draine4@gmail.com
description: Welcome to my Website!<br /> NYC- Based Violist
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Sugar Hill
city: New York
state: NY
zip_code: 55555
country: USA
phone: (434) 944-8122

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed


collections:
  photo_gallery: