# site settings
title: Dudley Raine, IV
subtitle: homepage
email: draine4@gmail.com
description: Dudley <br/>NYC- Based Violist
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
city: New York
state: NY
country: USA
phone: (434) 944-8122

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/Draine4
instagram_url: http://instagram.com/dudzraine4
linkedin_url: https://www.linkedin.com/in/dudley-raine-iv-b73608ab/
500px_url: https://soundcloud.com/dudley-raine-iv

# build settings
markdown: kramdown

sass:
  style: compressed


collections:
  photo_gallery: